### ISSUE TITLE
adding a Conn_Coaxial library?

### ISSUE THREAD

**Issue by Shackmeister** [KiCad/kicad-footprints#100]
Hi guys
Wouldnt it make sense to have a library for all SMA, MCX, UFL etc connectors?

**Comment by poeschlr** [comment]
Yes see: https://github.com/KiCad/Connectors.pretty/issues/83#issuecomment-326804972

**Comment by Shackmeister** [comment]
should I wait for this library to be added or should I just make a PR which adds the library together with the component?

**Comment by poeschlr** [comment]
Submit the pull request for you files within a newly created .pretty directory.
Add this lib to the fp-lib-table
Don't forget to add a Readme.md file

**Comment by Shackmeister** [comment]
https://github.com/KiCad/kicad-footprints/pull/103
done 

Thanks @poeschlr
