### ISSUE TITLE
Unsure how to interpret datasheet

### ISSUE THREAD

**Issue by gcormier** [KiCad/kicad-footprints#1010]
What are the two sections for? Is the outermost a pad, and the innermost a keep-out zone?

![image](https://user-images.githubusercontent.com/8388983/46818698-df769080-cd4f-11e8-822e-7ad09603a0a6.png)
https://www.molex.com/molex/products/datasheet.jsp?part=active/0528921033_FFC_FPC_CONNECTORS.xml

**Comment by evanshultz** [comment]
Yes, The boxes with cross hatching means "NO PATTERN" which is no copper in Molex parlance.

The boxes with parallel lines are the pads.

**Comment by gcormier** [comment]
Would this just be representing on the footprint with a keepout in Dwgs.User? Such as this existing footprint:

![image](https://user-images.githubusercontent.com/8388983/46819344-81e34380-cd51-11e8-8277-23c61b920da3.png)

**Comment by evanshultz** [comment]
Due to KiCad being devoid of what any respectable ECAD program would consider a capable design constraint system, yes. See http://kicad-pcb.org/libraries/klc/F4.5/.

**Comment by gcormier** [comment]
Dang. Yeah and drawing these lines, aligned, evenly spaced.... not much fun.
