### ISSUE TITLE
audio jack symbols use letters; footprints use digits

### ISSUE THREAD

**Issue by ppelleti** [KiCad/kicad-footprints#1012]
The footprints in `Connector_Audio.pretty` have numeric pin numbers, while the corresponding library symbols have alphabetic pin numbers.  This means they don't work together.

I first noticed this when I filed #979, but it also recently came up [on the forum](https://forum.kicad.info/t/connector-audio-stereojack-3-5mm-odd-pin-numbering/13038).

**Comment by evanshultz** [comment]
Thanks for bringing this up.

You are correct in the forum that using letters was most consistent across all manufacturers, provides some intelligence about the pin's use, and also differentiates between the connector pins that go to different jacks (the jacks connected to the cable and inserted into the connector) with combo connectors.

See https://github.com/KiCad/kicad-footprints/issues/191. I have made, I think, new footprints that will match the symbols and will also update any existing ones when I push them. I've been (slowly) gathering feedback and consensus before submitting that PR. It was a mistake to leave this hanging in the v5 libraries and cause this user issue. Apparently I should prioritize getting the footprints wrapped up.
