### ISSUE TITLE
PowerPAK 

### ISSUE THREAD

**Issue by jneiva08** [KiCad/kicad-footprints#1024]
The PowerPAK package is exclusive to Vishay.

When search PowerPAK in footprint editor get this results:

* PowerPAK_SO-8_Dual
* PowerPAK_SO-8_Single
* Vishay_PowerPAK_SO-8

It appear Vishay_PowerPAK_SO-8 is the same of PowerPAK_SO-8_Single.
Should be removed one of single?

**Comment by evanshultz** [comment]
With any apologies needed, I'm closing this. I already filed a similar issue with a proposal to resolve at https://github.com/KiCad/kicad-footprints/issues/1000. No response, yet, though. :(
