### ISSUE TITLE
Get ride of git history

### ISSUE THREAD

**Issue by Misca1234** [KiCad/kicad-footprints#1216]
Any goo tip to get ride of this 

![bild](https://user-images.githubusercontent.com/25547797/50441020-0f6a1480-08f9-11e9-9fcc-fed6d027917a.png)

I followed an earlier tip but it seems not to work, 
refork ?
update the the forked one in some way ?

**Comment by pointhi** [comment]
instead of merge do a ```git pull --rebase origin master```

To fix this you could pull the current master and do cherry picks, or a ```git rebase --interactie HEAD~13```

**Comment by Misca1234** [comment]
so, instead of 

```
git fetch upstream master
git merge upstream/master
```

I should before next push do

```
git fetch upstream master
git rebase --interactie HEAD~13

```

**Comment by poeschlr** [comment]
another option is 
```
git fetch upstream
git checkout upstream/master
git checkout -b new_branch
```

This will leave your personal master branch alone but still start you off at the right place for a new contribution.

**Comment by poeschlr** [comment]
If you want your personal master branch in synch with the official one then do as follows:

```
git fetch upstream
git checkout upstream/master
git branch -D master
git checkout -b master
git push --set-upstream origin master --force
```

And in future do the following regularly to keep your master branch in sync:
```
git checkout master
git pull upstream master
git push
```

**Comment by Misca1234** [comment]
I will try, it can not go much more wrong

**Comment by Schlumpf** [comment]
You can squash commits: https://help.github.com/articles/about-pull-request-merges/

**Comment by poeschlr** [comment]
does not fix his local history which is the question of this issue

**Comment by Misca1234** [comment]
> You can squash commits: https://help.github.com/articles/about-pull-request-merges/

The only invention worse than the squashing commits in git is git itself ;)

**Comment by poeschlr** [comment]
Git is a great tool. Like any other tool it requires the user to first learn and understand both how it works and what its limitations are.

Squash commits are a great feature especially for us. Users should not ammend commits such that we can see what changed after a review. We would however not really need all these small commits in the larger git history (i don't really care how long it took a user to get to a state that could be merged) That is where squashing comes in. We take the many commits by the contributor and squash them to one. Add a meaningful commit message and have a clean history but still the feature of seeing what changed after every round of feedbacks.

**Comment by Misca1234** [comment]
Greatness is not measured in the number of ways people can do things or how many "backdoors" there is.
Git is not a good solution for revision handling nor a collaboration tool (actually it is not a revision tool at all but a file handling system)
It is way over the top complicated for 90% of the use cases on github or gitlab

I do not favour clearcase or the svn-crap, it might be a great tool for file handling system for people on the run that meet each other in an airport hub with intervals of several years or similar.

On that point we disagree of the greatness of git

just look at 
```
git rebase --interactie HEAD~13
git push --set-upstream origin master --force
```
Why does a tool create a situation where it is necessary too have this kind of in deep knowledge to solve situations or even creating the possibility for the situation to occur where this is needed.

**Comment by poeschlr** [comment]
The problem is that you got your personal master branch out of sync with the global branch. I gave you a lot easier solution further above (the one where you simply ignore your local branch and directly branch away from the global branch)

I also gave you a more easily understood and most importantly more general solution to your current problem. (The lines you quoted only work because you have exactly 13 merges that should not be there. If you do anything else then you get into trouble.)

**Comment by poeschlr** [comment]
Maybe to explain my solution a bit more:

First we need to download the current state of the official repo:
`git fetch upstream`
now we need to locally switch to the current state of the official repo:
`git checkout upstream/master`
To be allowed to make changes we need a local branch under our control that we can then push to our fork (and use as a source for the new pull request) replace new_branch with a descriptive branch name.
`git checkout -b new_branch`

There are ways to combine the last two commands but i think the way i present it here is much clearer to understand.

If you always do it that way then it will become second nature. You will never be out of sync at the start of doing your changes.

If you however want your local master branch in sync with the official one then go with my second commend above.

**Comment by evanshultz** [comment]
There are GUI tools for git which abstract away the exact commands and (hopefully!) put a clear label on the operation that will be performed.

**Comment by Misca1234** [comment]
@poeschlr 
My comment is not a critique toward you, I appreciate the help you give me, 
it was against Git as such

> Why does a tool create a situation where it is necessary to have this kind of in deep knowledge to solve > situations or even creating the possibility for the situation to occur where this is needed.

This was not really a question that wanted an answer, it was to put light on a tool that allow a bad/unnecessary/never wanted  situation to be created in the first place.
