### ISSUE TITLE
RF_GPS.pretty

### ISSUE THREAD

**Issue by jneiva08** [KiCad/kicad-footprints#1242]
Recently was created GPS/GNSS folder for IC and Modules.
It's wise to move from RF_Module.pretty to RF_GPS.pretty?

I don't mind to have the task and fix the symbols

**Comment by poeschlr** [comment]
How many footprints would be affected?
How many of them where in the lib when v5 was released?

**Comment by jneiva08** [comment]
On v5 tag was only 2/3 (ublox SAM/SAM_handsoldering and Linx_RXM-GPS)
on V5.0.1 i have added ublox MAX, NEO and LEA

I think its all footprint

On symbol side is RXM-GPS-RM and ublox SAM-M8Q, recently was added ublox MAX, the neo and lea is still waiting and can be easily fixed

**Comment by poeschlr** [comment]
In this case go ahead.

**Comment by myfreescalewebpage** [comment]
PR merged, closing the issue.
