### ISSUE TITLE
MountingHole library should be renamed Mechanical

### ISSUE THREAD

**Issue by myfreescalewebpage** [KiCad/kicad-footprints#1245]
Following the addition of #1041 I would suggest that the MountingHole library should be renamed Mechanical. This is more consistent with the symbol library which is already named Mechanical (in which enclosure, heatsink, holes and din rail adapter are available).

Any objections ?

Cheers,
Joel

**Comment by poeschlr** [comment]
It is to be expected that we will have more footprints for these parts compared to symbols. It makes therefore a lot of sense to have a mechanical symbol lib that collects symbols for many very different mechanical parts. On the footprint side i would however prefer these to be split up.

**Comment by myfreescalewebpage** [comment]
Thanks @poeschlr 
So moving DIN rail in a new library, alone ?
Joel

**Comment by poeschlr** [comment]
Maybe something like `MountingEquipment` could be generic enough to include different specialized parts intended to mount the pcb to something.

**Comment by evanshultz** [comment]
Agree that `MountingHole` stays but this footprint doesn't fit.

What footprints are we likely to add? `MountingEquipment` is pretty broad so we could start there and see what other contributions come up. (I'm not in love with the name but don't have a betters suggestion right now.) If we get a lot more footprints and split up a library that's a lot of churn later on but we also don't want to start out with overly-specific libraries. `MountingRails` would be an option if we were likely to add more rail adapters. `MountingAdapters` would be even more generic to include rails and other stuff. Personally, I wouldn't predict a huge amount of contributions here and support Rene's suggestion unless we can come up with a more elegant name.

**Comment by myfreescalewebpage** [comment]
@evanshultz totally agree with you, we cannot say what will be proposed in the future, so let's go with `MountingEquipment`.

I will make the modification for this DIN rail part soon.

Joel

**Comment by myfreescalewebpage** [comment]
Done.

**Comment by myfreescalewebpage** [comment]
@poeschlr you have merged the footprint but not the 3D package. See above referenced PR. Probably we need also to close this issue once it is done ;)

Cheers,
Joel
