### ISSUE TITLE
Schurter 0031 8002 fuse holder is not 5x20mm (footprint name)

### ISSUE THREAD

**Issue by mgottschlag** [KiCad/kicad-footprints#1267]
While drawing a new footprint I noticed that the "Fuseholder_Cylinder-5x200mm_Schurter_0031-8002_Horizontal_Open" footprint is much bigger than my new 5x20mm fuse holder footprint. Indeed, it seems to be a 6.3mmx32mm fuse holder, the name should be changed accordingly.

**Comment by Misca1234** [comment]
This have been addressed in 
https://github.com/KiCad/kicad-footprints/pull/1295
closing
