### ISSUE TITLE
DS2401P is missing a TSOC 6 footprint

### ISSUE THREAD

**Issue by antoniovazquezblanco** [KiCad/kicad-footprints#1280]
While improving the library in https://github.com/KiCad/kicad-symbols/pull/1385, it has been found that we are missing a TSOC footprint.

Documentation:
https://pdfserv.maximintegrated.com/en/ds/DS2401.pdf
https://pdfserv.maximintegrated.com/land_patterns/90-0321.PDF
https://pdfserv.maximintegrated.com/package_dwgs/21-0382.PDF

**Comment by jneiva08** [comment]
the PR for the footprint is https://github.com/KiCad/kicad-footprints/pull/1248

**Comment by antoniovazquezblanco** [comment]
sorry! havent seen that!
