### ISSUE TITLE
Git history went backwards

### ISSUE THREAD

**Issue by fauxpark** [KiCad/kicad-footprints#1313]
I have these commits in my fork which are not in upstream:

![untitled](https://user-images.githubusercontent.com/4781841/51419021-5d61f780-1bdb-11e9-914a-64ca16ad4523.png)

**Comment by poeschlr** [comment]
Hm i fear @Shackmeister might have some explaining to do.

![screenshot from 2019-01-19 01-19-53](https://user-images.githubusercontent.com/18327350/51419154-75f4f200-1b88-11e9-823c-eb5260f67b84.png)

**Comment by Shackmeister** [comment]
@poeschlr I'm afraid he has aswell. Was catching up on my local repo and I must have accidently pushed to master. Very sorry for the trouble

**Comment by poeschlr** [comment]
@fauxpark i pushed the state of your fork to the main repo.

@Shackmeister did your now remove push possibility from your local copy?
check by running git remote -v
make sure there is no legal link for the (push) option of the main repo.

**Comment by poeschlr** [comment]
I think i got everything back in that was lost. (There where only 3 pull requests merged after @fauxpark pulled from the repo.)

Thanks @fauxpark for reporting this so fast. Made it possible to be fixed quite easily.

**Comment by Shackmeister** [comment]
I have now disabled push to all the kicad repos

@fauxpark @poeschlr Sorry for the mess, and thanks for cleaning it up.
Is there a reason we haven't disabled it "globally"? If it's needed sometimes for cleanup I suppose it could just be enabled when needed and otherwise left off? not trying to cover my own stupidity, but just curious

**Comment by poeschlr** [comment]
What should we disable globally? You having push rights is what allows you to merge pull requests. If i turn that off for you then you can no longer merge contributions defeating the purpose of being a maintainer.

**Comment by Shackmeister** [comment]
makes sense, thought the merge and push was considered 2 seperate actions (but now that I think about its makes sense its both)

**Comment by poeschlr** [comment]
There is no option i can see for disallowing force pushes. I know that gerit has such a feature but i can not see one on github.
