### ISSUE TITLE
TE connectivity repo is archived without notifying the contributors of open pull requests about that fact

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-footprints#132]
@SchrodingersGat i don't know a better place to place this. (I can't open an issue nor can i comment on the still open pull requests.)
Can you notify them about the fact that they should commit their stuff to this repo if they are still interested?

**Comment by SchrodingersGat** [comment]
Thanks, I have unarchived this such that those contributors can be notified. Oversight on my part.

**Comment by poeschlr** [comment]
Thanks.
