### ISSUE TITLE
Should we create a separate library that captures all FFC/FPC connectors?

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-footprints#134]
A lot of manufacturer seem to create such connectors. Currently we have footprints for connectors by at least Molex, TE and Hirose.

I would suggest a new lib called Connector_FFC-FPC and group them in there.
Naming of footprints would then be `[man]_[mpn]_{1xN or 2Rows_Npins}_[orientation]`

**Comment by evanshultz** [comment]
Did we come up with a good naming convention if the pins are staggered and an uneven quantity?

**Comment by poeschlr** [comment]
I don't know if it is good but currently we use 2Rows_NPins i think.

**Comment by SchrodingersGat** [comment]
I think this is a good idea
