### ISSUE TITLE
Solder jumpers with custom pads use zone connect none

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-footprints#1341]
See: https://forum.kicad.info/t/zone-fill-not-connecting-gnd/14904/

**Comment by JacobEFO** [comment]
Do you just want the pad 3 connection set to solid instead of none?

**Comment by evanshultz** [comment]
All custom pads need the zone connection set to solid as shown in the forum post.

I submitted a fix at https://github.com/KiCad/kicad-footprints/pull/1351 and tagged it for inclusion in 5.1.
