### ISSUE TITLE
duplicate of wuerth card connector

### ISSUE THREAD

**Issue by pointhi** [KiCad/kicad-footprints#141]
We have three card connectors with the same manufactur number, but different writing:

* https://github.com/KiCad/kicad-footprints/blob/master/Connector_Card.pretty/microSD_HC_Wuerth_693072010801.kicad_mod
* https://github.com/KiCad/kicad-footprints/blob/master/Connector_Card.pretty/microSD_HC_Wurth_693072010801.kicad_mod
* https://github.com/KiCad/kicad-footprints/blob/master/Connector_Card.pretty/MicroSd_Wurth_693072010801.kicad_mod

**Comment by SchrodingersGat** [comment]
Correct naming should be:

`MicroSD_HC_Wuerth_69.....`
