### ISSUE TITLE
Footprint Misnamed: Jack_3.5mm_Neutrik_NMJ6HCD2_Horizontal

### ISSUE THREAD

**Issue by gkeeth** [KiCad/kicad-footprints#1549]
The footprint Connector_Audio/Jack_3.5mm_Neutrik_NMJ6HCD2_Horizontal is misnamed. This is a 1/4" (6.35mm) jack, not a 3.5mm jack.

For reference: https://www.neutrik.com/en/product/nmj6hcd2

I imagine the footprint can simply be renamed, i.e. Jack_6.35mm_Neutrik_NMJ6HCD2_Horizontal.

If any symbols call out this footprint, they'll need to be updated as well. "grep Jack_3.5mm_Neutrik *.lib" doesn't reveal any symbols that specify this footprint, but is there a better way to check?

**Comment by evanshultz** [comment]
Thanks for this report.

This is a known issue and my PR at https://github.com/KiCad/kicad-footprints/pull/1145 will fix this problem. Since a fix is already in the works and it's a known issue I'll close this.
