### ISSUE TITLE
What should we do with the wire pads footprint lib?

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-footprints#158]
The test point lib has been transferred in https://github.com/KiCad/kicad-footprints/pull/52
The question about the wire pads lib has been raised in that pull request already.

**Comment by SchrodingersGat** [comment]
I think that wire pads are functionally separate from e.g. test points, so we should add a new library e.g. `WirePad`

**Comment by poeschlr** [comment]
I found an old discussion where you suggested the name Connector_Wire. (Would make more sense.)
https://github.com/KiCad/Wire_Pads.pretty/issues/5

I think i will for now use that name for it.

---

In that issue the deprecated lib [Wire Connection Bridges](https://github.com/KiCad/Wire_Connections_Bridges.pretty) is mentioned.
From the discussion i would amuse you meant to give it the name Connector_Jumper? (But under jumper i would understand this: https://i.stack.imgur.com/UsiJ3.jpg not https://circuitmaker.com/forum/posts/216769)
I think in that case `Wire_Bridge` would be better. In addition i don't think we currently have any true wire bridge footprints in our lib.
I guess a better idea would be for users to use vias and unused copper layer(s) to document the connections. (This would allow for doing this without needing to add a symbol to the schematic.)

In any case i think that particular discussion can wait until somebody does indeed contribute such a footprint.

**Comment by SchrodingersGat** [comment]
The way I see it, `Connector_` implies that some external "thing" will connect to the PCB. I think it also implies that this "thing" is removable, perhaps?

Jumpers do not fit this category IMO. By Jumpers I mean:

![image](https://user-images.githubusercontent.com/10080325/33606670-5def1e14-da12-11e7-89d1-0124b8142c2f.png)

![image](https://user-images.githubusercontent.com/10080325/33606673-61773a80-da12-11e7-9b96-d8de94db337a.png)

![image](https://user-images.githubusercontent.com/10080325/33606677-64af0020-da12-11e7-89f1-f2e305bc540d.png)

![image](https://user-images.githubusercontent.com/10080325/33606681-6788856e-da12-11e7-98de-241d48af9622.png)

![image](https://user-images.githubusercontent.com/10080325/33606709-7a25c5c4-da12-11e7-88ad-c8f8161831be.png)

**Comment by evanshultz** [comment]
To me, "wire pad" means a THT (very rarely a SMD) pad to which a wire is soldered. There is no other discrete component, just the wire.

In my vocabulary, here are the names of the items in the pictures above from top to bottom:
- Testpoint or testpad
- Jumper (this does not have a symbol or footprint since it fits on a header)
- Solder short
- Either a soldered jumper/bridge or a high-current, low-impedance sense resistor
- Either another soldered jumper/bridge or a high-current, low-impedance sense resistor

I agree that wire pads are a separate category and different from any of the pictures above. If I see a library named `WirePad` I would expect to see plated THTs named by either mm or AWG for fitting one or more wires.

**Comment by myfreescalewebpage** [comment]
@poeschlr @SchrodingersGat @evanshultz WirePad I have seen Connector_Wire has been created following this issue, do you still need to keep it opened ? Else I suggest the topic should be closed. Joel

**Comment by evanshultz** [comment]
I'm fine to close this then. However, I notice at least some (I didn't check all) seem to have converted dimensions because the names are "clean" mm sizes but the actual pad sizes have loads of significant digits.

**Comment by myfreescalewebpage** [comment]
Great catch, maybe something we can fix with a PR, I know several footprint have this problem... Some improvements of the travis checks for F5.3 (http://kicad-pcb.org/libraries/klc/F5.3/) should be great to check that:

> All courtyard line elements are placed on a 0.01mm grid
