### ISSUE TITLE
How to add

### ISSUE THREAD

**Issue by yelvlab** [KiCad/kicad-footprints#1626]
How to add teardrops pads?
my kicad version 5.1.2, but I cant use teardrops plugins [teardrops](https://github.com/svofski/kicad-teardrops),   anyone can help me?

**Comment by poeschlr** [comment]
This is the repo for the official kicad library. For support head over to the forum: https://forum.kicad.info/, to request a feature head over to the bugtracker: https://bugs.launchpad.net/kicad
