### ISSUE TITLE
Phoenix MC with 2,5 mm spacing

### ISSUE THREAD

**Issue by fbruetting** [KiCad/kicad-footprints#1669]
As those phoenix connector libraries are auto-generated – would you like to add the MC/MCV ones with 2,5 mm spacing, too? Would be nice, because these are more elegant for space-limited designs.

**Comment by poeschlr** [comment]
I agree that many of the phoenix connectors are still missing in the lib and they should be easily added to the script. We do however never accept requests for specific footprints as we would drown in issues of this kind. (the library project does not claim to have assets for all possible parts. If you are willing to invest time into this simply open a pull request both here and on the script repo.)
