### ISSUE TITLE
Courtyard placement question

### ISSUE THREAD

**Issue by gmsotavio** [KiCad/kicad-footprints#1738]
I have a really dumb question about KLC F5.3 (http://kicad-pcb.org/libraries/klc/F5.3/)

What is it supposed to do when these two requirements cannot be simultaneously satisfied:
1. All courtyard line elements are placed on a 0.01mm grid
2. Unless otherwise specified, clearance is 0.25mm

Must the clearance be 0.25 mm or may be close to 0.25 mm? Must the courtyard line be placed on a 0.01mm grid or preferable be placed on a 0.01mm grid?

**Comment by Shackmeister** [comment]
Round the 0.25mm to nearest 0.01 grid

**Comment by gmsotavio** [comment]
> Round the 0.25mm to nearest 0.01 grid

Thanks!
