### ISSUE TITLE
wrong sizes for R_1020

### ISSUE THREAD

**Issue by Shackmeister** [KiCad/kicad-footprints#174]
@poeschlr 
Hi Rene I noticed R_1020 and the handsoldering version both has a body size of 5x2.5mm, this seems quite big :)
can you look into it?

![r1020_1632_metric](https://user-images.githubusercontent.com/5279723/33800642-3e4a4af4-dd44-11e7-9930-095769a8295d.png)
![r1020_1632metric](https://user-images.githubusercontent.com/5279723/33800644-447e745e-dd44-11e7-8b6a-36576d0cc919.png)

**Comment by poeschlr** [comment]
Size is ok. But metric code is wrong.
![screenshot from 2017-12-10 14-11-34](https://user-images.githubusercontent.com/18327350/33805161-5eeb37da-ddb4-11e7-8128-f02602bc8981.png)

**Comment by poeschlr** [comment]
should be fixed now. @Shackmeister close this if you are satisfied.

**Comment by Shackmeister** [comment]
Sounds good, ill check it out tomorrow

**Comment by poeschlr** [comment]
@Shackmeister is this fixed to your satisfaction?

**Comment by Shackmeister** [comment]
Hi @poeschlr this is only fixed for the Hansoldering version, not the regular

**Comment by Shackmeister** [comment]
@poeschlr will you have time to fix this or should I do it? :)
