### ISSUE TITLE
Taiyo Yuden SMD inductor solder pads bigger than MF recommended

### ISSUE THREAD

**Issue by seppestas** [KiCad/kicad-footprints#1756]
The L_Taiyo-Yuden_NR-xxxx footprints do not seem to follow the manufacturer recommended landing patterns. All pads seem to be 0.2mm longer (Y axis) than recommended.

E.g, the length of the pads of the L_Taiyo-Yuden_NR-40xx footprint is 3.9mm in [this libraries KiCad module](https://github.com/KiCad/kicad-footprints/blob/cf71819ab37168bfad298de859b1bbd00f5a93f6/Inductor_SMD.pretty/L_Taiyo-Yuden_NR-40xx.kicad_mod), but it is only [supposed to be 3.7m according to the datasheet](https://www.yuden.co.jp/productdata/catalog/wound04_e.pdf).

Is this a mistake, or was this done to improve solderability?

**Comment by seppestas** [comment]
@SchrodingersGat it looks like [you generated these footprints "as per datasheet" in the original Inductors.pretty](https://github.com/KiCad/Inductors.pretty/commit/70424128869bbb13c27fcbccf8b3db344ec662a7).

Could you clarify if this is a mistake or intentional? If intentional, is there a rule for it?

**Comment by evanshultz** [comment]
@seppestas 
Thanks for bringing this up. That means it's an old footprint and subject to loose interpretation.

Making bigger pads could be helpful in some circumstances, but it should not be the expectation in this library if the footprint name or description don't indicate any deviation. We'll wait for @SchrodingersGat  to respond in case he can shed any light on this, but I'm of the mind the footprints should be updated to match the datasheet.

And note that the documentation linked in the original PR is not available. The parts do not match the _current_ datasheet, but that doesn't mean they weren't built correctly according to an older version of the datasheet.

Either way, I'm marking this as a bug.

**Comment by SchrodingersGat** [comment]
Hi guys, this was a fair while ago so I cannot specifically remember why this deviation was made. Sounds like a PR should be made to fix this.
