### ISSUE TITLE
Lower case "d" in Connector_Pin library

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-footprints#178]
KLC defines that diameters are prefixed with upper case "D".
Fixing this will also require fixing the 3d model names.

This has been discovered in https://github.com/KiCad/kicad-packages3D/pull/165

**Comment by strombom** [comment]
Made a pull request for this issue:

Footprints: https://github.com/KiCad/kicad-footprints/pull/337
Packages3D: https://github.com/KiCad/kicad-packages3D/pull/252

I could not find any related files in 3D sources and no references in symbols.

**Comment by Ratfink** [comment]
All the relevant PRs have been merged, so I believe this issue has been fixed.
