### ISSUE TITLE
WiFi modules in both RF_WiFi and RF_Module libraries

### ISSUE THREAD

**Issue by gmsotavio** [KiCad/kicad-footprints#1793]
Hi,

I noticed there are two libraries which have WiFi Modules. For example, the RF_Module has the ESP-07. On the other hand, RF_WiFi has the USR-C322. Both them are Wi-Fi/RF modules. In my understanding, USR-C322 should be moved to RF_Modules. The RF_WiFi should be populated with WiFi ICs, not modules. Is this thinking correct?

![image](https://user-images.githubusercontent.com/10669626/64057615-7cfbce00-cb75-11e9-9876-7eea17a28fa1.png)

**Comment by poeschlr** [comment]
The RF_WiFi library was added in https://github.com/KiCad/kicad-footprints/pull/1154

This was done as suggested by @myfreescalewebpage. This means we now need to move all wifi module from the rf_modules lib into this new one. (Not sure this is a good idea during a minor release cycle. especially as the rf_modules lib is not really that large to merit immediate splitting.)

**Comment by myfreescalewebpage** [comment]
Yes I have initiated this, GPS, GSM, etc was already here.
Module with WiFi + Bluetooth should probably be kept in RF_Module... or maybe RF_WiFi_Bluetooth ?
Anyway, I agree with @poeschlr that moving in minor release is not great, we should keep like that at the moment.
Joel

**Comment by gmsotavio** [comment]
I've got the point. Thanks for the clarifications. As @myfreescalewebpage, I also agree that moving at that time is not the best option. Maybe we can address this to v6.

Otavio

**Comment by antoniovazquezblanco** [comment]
It would be nice to have an issue with the required tasks to be performed and with milestone v6.0.0 assigned so that we can keep track of this. Can any of you guys do that?

Thanks!
