### ISSUE TITLE
[FR] SOD-123FA footprint

### ISSUE THREAD

**Issue by GMagician** [KiCad/kicad-footprints#1833]
From library I see a missing diode footprint, this package is used by Fairchild SF310FA.
I change F version and adapted to pad size/distance as reported by its datasheet (https://docs-emea.rs-online.com/webdocs/16cd/0900766b816cd10d.pdf).

Hope this may be used added.
[D_SOD-123FA.zip](https://github.com/KiCad/kicad-footprints/files/3590389/D_SOD-123FA.zip)

**Comment by poeschlr** [comment]
please open a pull request. we can not accept contributions in any other way.
