### ISSUE TITLE
BatteryHolder_Keystone_3034 does not make contact

### ISSUE THREAD

**Issue by 5N44P** [KiCad/kicad-footprints#1896]
I've manufactured some board with that footprint, but the contact with the battery fails, probably because of the soldermask thickness. 

Should i make a PR with a larger pad, as i made in #1622?

**Comment by chschlue** [comment]
With planar surface finishes, maybe even increasing it to match the cell's negative terminal diameter (and mask cut-out exceeding it) might be a good idea?

**Comment by poeschlr** [comment]
What does the battery holder manufacturer suggest? After all we build footprints after the manufacturers suggestions not necessarily to fit the constrains of one particular pcb manufacturing process.

**Comment by chschlue** [comment]
http://www.keyelco.com/product-pdf.cfm?p=798

![3034](https://user-images.githubusercontent.com/40901018/66272018-b9050b80-e864-11e9-9c91-8c41c29bf125.png)

Looks ridiculously tiny to me.

**Comment by chschlue** [comment]
IEC 60086-3 cell dimensions:

![iec86_0](https://user-images.githubusercontent.com/40901018/66272077-71cb4a80-e865-11e9-89e2-dd6809aeb142.png)
![iec86_1](https://user-images.githubusercontent.com/40901018/66272079-74c63b00-e865-11e9-8b76-8169c6c12025.png)
![iec86_2](https://user-images.githubusercontent.com/40901018/66272080-78f25880-e865-11e9-9379-694466f213df.png)

**Comment by 5N44P** [comment]
I'm having the problem even with HASL, so it's definitely a big issue here. I think we should not stick with the minimum. 

@chschlue i'm not very familiar with the IEC standards. For what i see, a cell with a 20mm that goes under the commercial de nomination of cr2032 has a negative contact diameter much bigger that 8mm. And if i recall correctly, the keystone 3034 is sold for those cells. 

I think a pad as big as the inner negative contact would work for sure, with no significant risks of short circuits

**Comment by chschlue** [comment]
I also think we should not stick with the minimum.
d4 in IEC 60086 is the minimum negative terminal diameter, the maximum depends on the cell's overall height:
![iec86_3](https://user-images.githubusercontent.com/40901018/66275006-ccc06a00-e884-11e9-854e-32e233334142.png)

All button cells I've ever seen appear to have a diameter close to the maximum and as it is (or should be) impossible to short it on the negative pad unless it is inserted in an angle over 45°, I don't see why the footprints shouldn't go with something in that neighborhood.

I can't publish the whole standard here but the screenshots should catch the essence.

**Comment by chschlue** [comment]
On a different note: Shouldn't battery holders have courtyards large enough actually insert the battery, analogous to connectors having enough clearance for mating?

**Comment by chschlue** [comment]
> I'm having the problem even with HASL, so it's definitely a big issue here.

Missed that before. So there seems to be no common manufacturing process left that could work reliably with the MF min recommendation.

**Comment by 5N44P** [comment]
> So there seems to be no common manufacturing process left that could work reliably with the MF min recommendation.

Maybe it's intended for a stencil that leaves paste also on the negative pad. But i didn't made any stencil, and at the moment i can't check if that pad is set for leaving the paste on the Paste layer

**Comment by chschlue** [comment]
Keystone 3000 and 3034 as well as Linx HLD-012 have paste on pad 2, but I assume that's an oversight.
Linx recommends a much larger pad, BTW.
https://linxtechnologies.com/wp/wp-content/uploads/bat-hld-012-smt.pdf

**Comment by 5N44P** [comment]
Also for 20mm cells: 
https://www.mouser.it/datasheet/2/238/bat-hld-001-1659379.pdf
This specific part looks like should be compatible with the keystone 3034 footprint, but with a 17.8mm pad
