### ISSUE TITLE
button switch wrong endpoint (?)

### ISSUE THREAD

**Issue by aster94** [KiCad/kicad-footprints#1994]
01:55:34: Processing courtyard of “Button_Switch_THT:SW_TH_Tactile_Omron_B3F-10xx”: Unable to find segment with an endpoint of (125.446 mm, 48.902 mm).

![image](https://user-images.githubusercontent.com/21184718/70366077-0e758d00-1895-11ea-9835-993a4237709c.png)

**Comment by chschlue** [comment]
Fixed in https://github.com/KiCad/kicad-footprints/pull/1856

**Comment by aster94** [comment]
Thanks!
