### ISSUE TITLE
Add open collector symbol

### ISSUE THREAD

**Issue by hildogjr** [KiCad/kicad-footprints#2051]
Some parts / symbols listed above could have added the "open collector symbol". This will improve the schematics (main in a printed version):
7405 and 06 http://www.ti.com/lit/ds/symlink/sn74ls06.pdf
74596
7433
7403
...

**Comment by evanshultz** [comment]
Brought up at https://github.com/KiCad/kicad-symbols/issues/2115. And it's a symbol thing not a footprint thing so this is the wrong repo.
