### ISSUE TITLE
wrong pin distance in Choke_Schaffner_RN202-04-8.8x18.2mm

### ISSUE THREAD

**Issue by HB9GKW** [KiCad/kicad-footprints#2076]
According to datasheet of common mode choke Schaffner RN202 the distance of pin 1/2 to 3/4 should be 15.2 mm while current library footprint has a pin distance of 10 mm.

**Comment by evanshultz** [comment]
Confirmed. The fab outline dimensions are correct and the pin X spacing is correct, but pin Y spacing is wrong as detailed above.

@HB9GKW 
Sorry for this error and thanks for reporting it. Would you submit a PR to fix this footprint?

**Comment by gkeeth** [comment]
Is this now fixed by #2079 ?

**Comment by evanshultz** [comment]
Ah yes. I believe it is. Thanks for posting!
