### ISSUE TITLE
Add new nucleo-144 footprint with arduino headers

### ISSUE THREAD

**Issue by fdila** [KiCad/kicad-footprints#2086]
The current footprint only has holes for morpho connector.
To design a shield stackable over arduino shield the arduino connectors should be present.
Like this footprint: https://www.snapeda.com/parts/NUCLEO-F746ZG/STMicroelectronics/view-part/?ref=search&t=nucleo

**Comment by chschlue** [comment]
Unfortunately, we're an understaffed team of volunteers and cannot take requests.
But it looks like you found what you're looking for at https://github.com/KiCad/kicad-footprints/pull/2045#issuecomment-583874715.
You're welcome to comment if you find mistakes in that PR.

Closing.
