### ISSUE TITLE
NMJ6HCD2 Listed as jack_3.5mm but is a 1/4 inch connector not 3.5mm

### ISSUE THREAD

**Issue by jimruxton** [KiCad/kicad-footprints#2096]
It looks like the NMJ6HCD2 connector in [this library](https://github.com/KiCad/kicad-footprints/tree/master/Connector_Audio.pretty) is labeled as a 3.5 mm connector when it's actually a 1/4 inch connector.

**Comment by evanshultz** [comment]
This issue will be fixed once https://github.com/KiCad/kicad-footprints/pull/1145 is merged.
