### ISSUE TITLE
SOT-343 footprint problem

### ISSUE THREAD

**Issue by hecko** [KiCad/kicad-footprints#2177]
As seen here: https://www.dropbox.com/s/ys10wnr0xtf07ft/Screenshot%202020-03-27%2013.35.17.png?dl=0 there is a problem with SOT-343_SC-70-4 package

**Comment by chschlue** [comment]
Confirmed.
Courtyard is not closed on _Handsoldering variant.

Would you be willing to submit a fix?

**Comment by hecko** [comment]
@chschlue no, Im sorry - Im unable to fix this at the moment. Possibly in one weeks time. Marcel

**Comment by evanshultz** [comment]
https://github.com/KiCad/kicad-footprints/pull/2179
