### ISSUE TITLE
Questions: Which pin is pin1 on a diode bridge rectifier?

### ISSUE THREAD

**Issue by jkriege2** [KiCad/kicad-footprints#224]
Hi!

I'm currently adding several diode bridges to the symbols, footpritns and 3D models. With the typical SIL-packages, I'm a bit stuck, as I'm not sure which pin to designate pin 1:
![2018-01-05 08_52_59-b40c2300 pdf geschutzt - adobe acrobat reader dc](https://user-images.githubusercontent.com/11967523/34600146-5029f668-f1f6-11e7-8aea-d132b20c758a.png)
Could you quickly state your preference?

For now I took the left pin, but currently I tend towards using the pin on the right, marked by the package bevel! This would also prevent us from the situation that pin1 is marked on the silkscreen, but the package has a mark at pin 4 ...

Best,
JAN

**Comment by SchrodingersGat** [comment]
Can you provide a datasheet for one of these packages? I assume that these are not simply the "standard" SIP package?

**Comment by jkriege2** [comment]
e.g. https://diotec.com/tl_files/diotec/files/pdf/datasheets/b40c700040.pdf

**Comment by jkriege2** [comment]
or http://www.vishay.com/docs/88657/kbu6.pdf

**Comment by pointhi** [comment]
I would also tend to the body bevel on the right, because the datasheet doesn't specify a pin 1, and it's the visual noticable side where people normally assume pin 1 is located.

**Comment by jkriege2** [comment]
OK! I think I'm going to rotate all packages as follows:
[2018-01-05 14_08_30-3d viewer](https://user-images.githubusercontent.com/11967523/34610557-fe1fc16e-f221-11e7-8b67-0c8a8f13d778.png)

**Comment by SchrodingersGat** [comment]
Agreed. One of the examples had a longer pin ok the right side also. Definitely should be pin 1

**Comment by jkriege2** [comment]
OK, so I tagged the marked pin (package bevel or longer pin) as pin 1, but in the footprint put them on the left to fulfil KLC (pin 1 top-left).

I will add some more of  these and post at some point in the  next week I think!
