### ISSUE TITLE
Connector_IEC_DIN

### ISSUE THREAD

**Issue by SchrodingersGat** [KiCad/kicad-footprints#228]
This legacy library has now been archived but the footprints still need to be transferred across to here..

**Comment by poeschlr** [comment]
The generator scripts have not yet been merged. They are also not easily changed to fit new requirements. So i would suggest we move them over as they are right now and document remaining KLC problems in an issue. (One of the problems is the naming of the footprints.)

**Comment by SchrodingersGat** [comment]
Are you able to take care of the transfer of these, Rene?

**Comment by MRQ** [comment]
Are you referring to this generator script?: https://github.com/pointhi/kicad-footprint-generator/pull/101
You might have seen that I changed the naming. My rule is documented in the [generator script](https://github.com/pointhi/kicad-footprint-generator/pull/101/files#diff-090538bdac423c1b360263be38755ab2R14).

**Comment by poeschlr** [comment]
Regarding naming, see http://kicad-pcb.org/libraries/klc/F3.6/ section `Connectors with Standardised Shape`

> Many connectors are provided by multiple manufacturers in an industry standard package or physical layout. These connectors should use the accepted industry naming at the beginning of the footprint name:
`[Standard]-[Pins]_[Series modifier]_[MAN]_[Series]_[MPN]_[Pin layout]_P[Pitch]_[Modifiers]_[Orientation]_[Options]`

In your case it should be at least:
`[Standard]-[Pins]_[Pin layout]_P[Pitch]_[Orientation]` (Pin layout only for connectors that have missing pins)

**Comment by poeschlr** [comment]
The footprints in question have been merged.
