### ISSUE TITLE
Cannot connect copper zone to tab of Package:SO:ONSemi_SO-8FL_488AA

### ISSUE THREAD

**Issue by m-schubert** [KiCad/kicad-footprints#2347]
Opening this issue, because I'm not certain whether this was intentional or not. Perhaps @Shackmeister could comment?

Pad 5 (the tab) of this footprint has the "Pad connection" setting of "Connection to Copper Zones" set to None:
![image](https://user-images.githubusercontent.com/14815122/85961690-c8be1480-b9de-11ea-8f00-4ec28c1306dd.png)

This means when adding a copper pour for heatsinking purposes, it isn't connected. I'd have thought that, given it's a thermal pad, that allowing copper zones to connect would be beneficial?

**Comment by evanshultz** [comment]
Known issue. This is a limitation of KiCad. Set that to 'Zone' and it will connect. Custom pads can't have thermal spokes. Check the KiCad issue list for this request and pile on if you like.
