### ISSUE TITLE
FSDH321L and FSDL321L are missing an 8LSOP package

### ISSUE THREAD

**Issue by antoniovazquezblanco** [KiCad/kicad-footprints#235]
Datasheet: https://www.fairchildsemi.com/datasheets/FS/FSDH321.pdf

Components FSDH321L and FSDL321L available at the symbols repo (Converter_ACDC) are missing a footprint.

**Comment by antoniovazquezblanco** [comment]
If at least we can agree on naming for the footprint here I can add it to the symbol in the current PR. Any suggestions @SchrodingersGat?

**Comment by poeschlr** [comment]
Regarding naming see: http://kicad-pcb.org/libraries/klc/F3.4/ (Gull wing)

I think these might be possible as generic footprints so no need for a manufacturer prefix.
I assume they will be part of the SOIC lib and named `LSOP-8_ ...`

**Comment by antoniovazquezblanco** [comment]
I guess then it would be `LSOP-8_6.4x9.7mm_P2.54mm`.

Thank you very much @poeschlr.

**Comment by stephf0716** [comment]
I am working on the footprint. 
@antoniovazquezblanco 
Shouldn't name be `LSOP-8_6.4x9.2mm_P2.54mm`?
![image](https://user-images.githubusercontent.com/2642727/35190599-50055300-fe1a-11e7-9ea4-47fe2a134ee1.png)

**Comment by antoniovazquezblanco** [comment]
@stephf0716 you are right! Sorry! I will fix the footprint filter in the component. Thank you very much for your help ;)

**Comment by stephf0716** [comment]
@antoniovazquezblanco I will use `Fairchild_8LSOP`

**Comment by poeschlr** [comment]
`Fairchild_LSOP-8` would fit the rest of the library better.
