### ISSUE TITLE
Footprint for SMD 5730 YUJI LEDS seems inverted 

### ISSUE THREAD

**Issue by zackles** [KiCad/kicad-footprints#2373]
Hello,
I just use the footprint LED_SMD:LED_YUJI_5730 and it seems it is inverted for his association with its symbol.

Datasheet is here :
https://cdn.shopify.com/s/files/1/0344/6401/files/YJWJ005-1.1_YJ-VTC-5730-G01.pdf?7088009637272241372

Could someone verify with me if it is indeed an error?

**Comment by zackles** [comment]
![2020_07_24_11_57_08_](https://user-images.githubusercontent.com/11263148/88380517-0119fe00-cda5-11ea-9320-3594320090b8.png)
Here is a picture making the comparaison between kicad output and datasheet

**Comment by aris-kimi** [comment]
Hi @zackles , from the top view from datasheet image, polarity seems ok to me.

**Comment by zackles** [comment]
Hi @aris-kimi, Thank you for your quick review. I agree with your interpretation. Will you update the footprint?

**Comment by aris-kimi** [comment]
I will create a PR later if you do not want to give it a try. :-) But later tonight, so if you change your mind in the meantime, feel free to propose a fix.

**Comment by zackles** [comment]
I may try to edit the footprint (not so hard I think) but I need to refresh my github skill ;p I'm looking at that right now.

**Comment by zackles** [comment]
I don't understand why this previous PR did'nt corrected the problem
https://github.com/KiCad/kicad-footprints/pull/1948

**Comment by aris-kimi** [comment]
Well... It did.. In my footprint libraries this footprint is correct. So i guess your library files ore not up to date..
This mean this issue can now close.. :-) Thank you for notice that..

**Comment by zackles** [comment]
My Bad!  I have the 5.1.5 version. I'm installing 5.1.6 that include the corrected footprint

**Comment by zackles** [comment]
My Bad!  I have the 5.1.5 version. I'm installing 5.1.6 that include the corrected footprint

**Comment by zackles** [comment]
Thank you aris-kimi for your help.
5.1.6 version works for YUJI_5730 LED.
