### ISSUE TITLE
VIPer25LN and VIPer25HN are missing a DIP-7 footprint from ST

### ISSUE THREAD

**Issue by antoniovazquezblanco** [KiCad/kicad-footprints#243]
Datasheet: http://www.st.com/content/ccc/resource/technical/document/datasheet/52/fe/bc/a1/69/06/49/08/CD00231127.pdf/files/CD00231127.pdf/jcr:content/translations/en.CD00231127.pdf

My name proposal is `ST_DIP-7_6.35x9.27mm_P2.54mm`.

**Comment by jkriege2** [comment]
Just use the existing `PowerIntegrations_PDIP-8B`

**Comment by jkriege2** [comment]
![2018-01-10 15_38_56-3d viewer powerintegrations_pdip-8b](https://user-images.githubusercontent.com/11967523/34778038-6752a9be-f61c-11e7-8acd-e42420c85b7c.png)

**Comment by antoniovazquezblanco** [comment]
Solved, thanks @jkriege2!
