### ISSUE TITLE
Incorrect pin numbering on Molex Pico-Lock 504050 series connectors

### ISSUE THREAD

**Issue by justyn** [KiCad/kicad-footprints#2465]
The pin numbering of the 1.5mm pitch versions of the Molex Pico-Lock 504050 connectors is backwards.

The files are in this repository at `Connector_Molex.pretty/Molex_Pico-Lock_504050-**91_1x0*-1MP_P1.50mm_Horizontal.kicad_mod`.

The connector family page is [here](https://www.molex.com/molex/search/deepSearch?pQuery=category%253A%2522PCB%2BHeaders%2522%2540orientation%253A%2522Right%2BAngle%2522%2540pitchmatinginterface%253A%25221.50mm%2522%2540productname%253A%2522Pico-Lock%2522), the datasheet [here](https://www.molex.com/pdm_docs/sd/5040500291_sd.pdf).

As well as the numbering being specified in the datasheet, circuit 1 is also marked with a physical indicator on the connectors.

These footprints are generated using [kicad-footprint-generator](https://github.com/pointhi/kicad-footprint-generator), using [smd_single_row_plus_mounting_pad.py](https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Connector/Connector_SMD_single_row_plus_mounting_pad/smd_single_row_plus_mounting_pad.py) with values from [conn_molex.yaml](https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Connector/Connector_SMD_single_row_plus_mounting_pad/conn_molex.yaml).

The fix is really simple, the value [here](https://github.com/pointhi/kicad-footprint-generator/blob/491dfee3abab24f1449327aae393530a9c6d4fa2/scripts/Connector/Connector_SMD_single_row_plus_mounting_pad/conn_molex.yaml#L321) for `pad1_position` must be changed from `bottom_left` to `top_left`.

I'd be happy open a PR with the fixed footprints but I'm not sure what the process is given that changing the pin numbering would break any existing designs.

This issue came up because I am trying to add the 2mm pitch version of this family ([PR here](https://github.com/pointhi/kicad-footprint-generator/pull/625)).

![image](https://user-images.githubusercontent.com/203419/93018467-d6d80600-f5c7-11ea-92bb-0a83e8a54039.png)

![image](https://user-images.githubusercontent.com/203419/93018469-db9cba00-f5c7-11ea-8aac-2f4749d026f4.png)

**Comment by chschlue** [comment]
> I'd be happy open a PR with the fixed footprints but I'm not sure what the process is given that changing the pin numbering would break any existing designs.

This is a severe bug and footprints are also embedded in board files, so existing design won't get broken.
A fix is very welcome.
Note to self: Cherry-pick to v5.
