### ISSUE TITLE
Footprints with complex pad shapes would benefit from the use of polygon pads.

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-footprints#266]
Polygon pads result in better paste and mask handling then overlapping pads.

The downsides are:
- not compatible with version 4. (But we already have ~~some~~ **many** libs that include rounded rectangles. This already results in invalid libs.)
- ~~currently not handled by stepup which makes checking footprint correctness a lot harder.~~

Edit: Adding list:
- [x] SOT-89s https://github.com/KiCad/kicad-footprints/tree/master/Package_TO_SOT_SMD.pretty
- [x] Texas_X2SON-4_1x1mm_P0.65mm.kicad_mod (https://github.com/KiCad/kicad-footprints/pull/521)
- [x] Infineon MLPQs and PQFNs at https://github.com/KiCad/kicad-footprints/tree/master/Package_DFN_QFN.pretty
- [x] Package_DFN_QFN.pretty: QFNs with odd-shape corner pads (https://github.com/KiCad/kicad-footprints/issues/658; implemented in script)
- [x] Jumper.pretty (Fix: #716)
- [x] RF_Shielding.pretty (open PR at https://github.com/KiCad/kicad-footprints/pull/890)
- [x] Coilcraft LPS4018 (https://github.com/KiCad/kicad-footprints/pull/257)

**Comment by evanshultz** [comment]
If for no other reason than I would probably forget if I didn't write it down, here are a few footprints (or footprint families) that would benefit:
- SOT-89 at https://github.com/KiCad/kicad-footprints/tree/master/Package_TO_SOT_SMD.pretty
- https://github.com/KiCad/kicad-footprints/blob/master/Package_SON.pretty/TI_X2SON-4_1x1mm_P0.65mm.kicad_mod (this one also needs the prefix changed from TI_ to Texas_)
- Infineon MLPQs and PQFNs at https://github.com/KiCad/kicad-footprints/tree/master/Package_DFN_QFN.pretty

**Comment by pointhi** [comment]
Lets start a list of libraries which use the old system and could profit from polygon pads:

* **Jumper.pretty** Fix: https://github.com/KiCad/kicad-footprints/pull/716
* **RF_Shielding.pretty**
* ... (please add other libraries you know)

**Comment by evanshultz** [comment]
List started above.

**Comment by evanshultz** [comment]
I've fixed all the outstanding items I could find above and DFN/QFN (that aren't scripted) and TO/SOT at https://github.com/KiCad/kicad-footprints/pull/981. Except for the one Wuerth SMD inductor noted in that PR where I haven't figured out how to make the footprint from FreeCAD. And Rene's PR that is modifying the RF shields.

Is there another footprint or topic that this issue should cover, or can this be closed when the aforementioned two PRs (mine + Wuerth inductor and Rene's) are merged?

**Comment by evanshultz** [comment]
All of the list above is done, many of the #981 items have been merged (broken apart into separate PRs) and that includes the inductor.
