### ISSUE TITLE
Shouldn't this repo be pinned to frontpage? 

### ISSUE THREAD

**Issue by Shackmeister** [KiCad/kicad-footprints#29]
See above :)

**Comment by poeschlr** [comment]
I think it is a bit early for this. (When we have a bit more stuff in this repo then yes.)

**Comment by Shackmeister** [comment]
Fair nuff :)

**Comment by poeschlr** [comment]
I think now that we have transferred nearly all libs we can do this.

**Comment by SchrodingersGat** [comment]
It already is... :)

**Comment by poeschlr** [comment]
Oh ... (I should have looked before raising this again)
