### ISSUE TITLE
Release the footprints

### ISSUE THREAD

**Issue by leventelist** [KiCad/kicad-footprints#299]
Is it intentional that the footprints repository has no tags that corresponds to any KiCad releases? So it is somewhat rolling release. It could be helpful to tag a specific commit for a specific KiCad release.

**Comment by poeschlr** [comment]
This repo holds footprints for the v5 release. (See readme.md file) You might have noticed that kicad 5 has not yet been released.

**Comment by poeschlr** [comment]
You might want to take a look at https://forum.kicad.info/t/how-can-i-install-a-specific-version-of-the-footprint-library/9269 for a more detailed explanation.

Or on the library download page (a short note) http://kicad-pcb.org/libraries/download/

I will make this more clear on the download page.

**Comment by stephf0716** [comment]
@poeschlr Perhaps this should be bolded/highlighted/all caps in the repo information and the README? Same for the other KiCad 5 lib repos.

**Comment by poeschlr** [comment]
Ok i will try that. I will also make it more clear on the library download page over on the github library.

**Comment by leventelist** [comment]
On Tue, 23 Jan 2018 23:35:04 +0000 (UTC)
Stephanie <notifications@github.com> wrote:

> @poeschlr Perhaps this should be bolded/highlighted/all caps in the
> repo information and the README? Same for the other KiCad 5 lib repos.
> 

Thanks, I missed that. Now this is clear.


Levente

**Comment by poeschlr** [comment]
The information that these repos are for kicad 5 has been added everywhere where i could add it.
