### ISSUE TITLE
TDSON-8-1 has paste pads with pin numbers

### ISSUE THREAD

**Issue by strombom** [KiCad/kicad-footprints#312]
Suggestions:
* Remove pin numbers from paste pads
* Remove copper from paste pads
* Remove paste layer from exposed pad

![image](https://user-images.githubusercontent.com/875166/35488621-a780d7e0-048b-11e8-80e8-61ce8b2ad521.png)

https://github.com/KiCad/kicad-footprints/blob/master/Package_TO_SOT_SMD.pretty/TDSON-8-1.kicad_mod

**Comment by poeschlr** [comment]
Fixed in https://github.com/KiCad/kicad-footprints/pull/329
