### ISSUE TITLE
SSOP-8 package/footprint name

### ISSUE THREAD

**Issue by strombom** [KiCad/kicad-footprints#331]
I'm making a 3D-model/footprint for an optocoupler:
http://www.cel.com/pdf/datasheets/ps8802.pdf

It seems that the script will be able to create this part. 

Name suggestion:
SSOP-8_3.95x5.21mm_P1.27mm

Should I include height in the part number?
SSOP-8_3.95x5.21x3.27mm_P1.27mm

**Comment by poeschlr** [comment]
The height is optional. I think we should only include it if this particular part is higher than a normal ssop package.
