### ISSUE TITLE
Invalid Relay_THT.pretty

### ISSUE THREAD

**Issue by devimc** [KiCad/kicad-footprints#332]
failed to add Relay_THT.pretty using Footprint Libraries Wizard, status is invalid
this issue was introduced in commit 3d2333e767985db8a7a4d0ec29773c57378e3250
last stable commit is 219a50eada1212b9fd89c54d4e72547cbdbce3d5

Kicad version 4.0.4-stable
wxWidgets: 3.0.2
Platform: Linux 4.12.12-gentoo x86_64

**Comment by poeschlr** [comment]
The libs in this repo are intended for kicad version 5 and use features that are not supported in kicad version 4.

This is explained on the official kicad library download page http://kicad-pcb.org/libraries/download/
In the github download pages (linked from the official page), the Readme.md files of all affected repos and in the repo description.

See the kicad library download page for a description on how to get the libs for version 4.
If we are motivated we might make a backport of this lib once kicad version 4 is released.
