### ISSUE TITLE
LFCSP-8-1EP_2x3mm_P0.5mm wrong name

### ISSUE THREAD

**Issue by jcyrax** [KiCad/kicad-footprints#336]
I think it should be names LFCSP-8-1EP_3x2mm_P0.5mm, but maybe I don't quite understand.

Are the body dimensions x/y always from orientation with pin 1 in upper left?

This is how it looks now:
![image](https://user-images.githubusercontent.com/16546947/35694266-7041b2bc-0789-11e8-886f-62b7e0ad2f09.png)

**Comment by poeschlr** [comment]
If this footprint has indeed that name in the current head than it is wrong.

Not only are the body dimensions wrong but the name should also include the size of the exposed pad.

**Comment by Ratfink** [comment]
Fixed by #354.
