### ISSUE TITLE
Copy KLC footprint chapter into this wiki

### ISSUE THREAD

**Issue by matyro** [KiCad/kicad-footprints#346]
It would be nice to add the Library convention section with the footprint guidelines into this project wiki. This makes it easier to find and faster to access.

https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention

**Comment by poeschlr** [comment]
Why would this be faster to access? 
There is a direct link from this wiki page to the KLC section of the homepage. (In bold font)

Having two places for the same information adds a lot of maintenance effort, and an additional place for errors to sneak in. All of this for little to no gain.

**Comment by matyro** [comment]
Ok to say the truth I never scrolled down until the links appear. I only clicked on the wiki button (which does not work by the way) and locked there for up to date information.

**Comment by poeschlr** [comment]
Oh you mean we should make a wiki on the new repos. (you linked the old repos wiki so i was a bit confused how you could miss the bold notice about it being deprecated and the link to the new stuff.)

**Comment by matyro** [comment]
Yes,
I talked about this repositorys wiki. Sorry for the confusion.

**Comment by poeschlr** [comment]
A wiki just to link to the official kicad homepage is overkill. Added a link to the KLC in the readme this has to be enough.
