### ISSUE TITLE
Some THT resistor footprints have wrongly placed fab drawings.

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-footprints#393]
I noticed that some tht resistor footprints have their fab outline on the wrong position.
Some examples:
![screenshot from 2018-02-23 01-16-26](https://user-images.githubusercontent.com/18327350/36571602-ce749016-1837-11e8-8128-9d874cded469.png)

There are also some where the courtyard does not quite fit. (For these it seems that not only the fab outline is placed wrong but also the silk outline.)
![screenshot from 2018-02-23 01-16-32](https://user-images.githubusercontent.com/18327350/36571609-dbce0d46-1837-11e8-8a99-232a8c43c68a.png)

**Comment by jkriege2** [comment]
fix available here: https://github.com/KiCad/kicad-footprints/pull/394
