### ISSUE TITLE
5.0.0-rc1 repository unusable on Linux

### ISSUE THREAD

**Issue by calebns** [KiCad/kicad-footprints#396]
After cloning the fresh repo, the git sees that the file WDFN-8-2x2mm is not staged for commit.
![image](https://user-images.githubusercontent.com/6149020/36691192-bebcecb8-1b34-11e8-833a-c6b6611650ae.png)

It seems that it contains invalid line endings which makes the Linux git to interpret the file as being changed. What suprises me, the git-2.7.4 gets crazy at this point and refuses to either check out anything or to unstage/revert changes to that file.
The following patch fixes the issue by removing 0xD character from line endings, i.e. makes the line endings compatible with the one found in other files.

[0001-test.log](https://github.com/KiCad/kicad-footprints/files/1760029/0001-test.log)

**Comment by jkriege2** [comment]
could you please open  a PR for the fix you proposed?

Thanks,
JAN

**Comment by poeschlr** [comment]
Fix merged
