### ISSUE TITLE
Molex_KK-6410 has wrong SilksS/Fab layer

### ISSUE THREAD

**Issue by pointhi** [KiCad/kicad-footprints#402]
Every SilkS part is inside the Fab layer, which automatically means at least one of the layers is wrong

**Comment by poeschlr** [comment]
Are you sure you look at the footprints in this repo? I just checked the one called `Molex_KK-254_AE-6410-03A_1x03_P2.54mm_Vertical` from the current master.

Looks ok to me: (Yellow is the fab layer, light blue is the silk screen)
![screenshot from 2018-03-04 00-50-45](https://user-images.githubusercontent.com/18327350/36940606-709d5b56-1f46-11e8-87b2-bdfaeace6ce3.png)

**Comment by pointhi** [comment]
you are correct. This happens when you name the legacy directory ```kicad-footprints```
