### ISSUE TITLE
Add missing footprints for Atmel MCUs

### ISSUE THREAD

**Issue by fauxpark** [KiCad/kicad-footprints#417]
Follows KiCad/kicad-symbols#340.

There are a number of missing QFN footprints for some Atmel MCUs. These should be based on [Atmel Appnote 8826](http://ww1.microchip.com/downloads/en/AppNotes/Atmel-8826-SEEPROM-PCB-Mounting-Guidelines-Surface-Mount-Packages-ApplicationNote.pdf).

- [ ] Package_DFN_QFN:DFN-10-1EP_3x3mm_P0.5mm_EP1.75x2.7mm (1)
- [ ] Package_DFN_QFN:QFN-20-1EP_3x3mm_P0.45mm_EP1.6x1.6mm (4)
- [ ] Package_DFN_QFN:QFN-20-1EP_4x4mm_P0.5mm_EP2.25x2.25mm (9)
- [ ] Package_DFN_QFN:QFN-28-1EP_4x4mm_P0.45mm_EP2.25x2.25mm (2)
- [ ] Package_DFN_QFN:QFN-32-1EP_4x4mm_P0.4mm_EP2.9x2.9mm (1)
- [ ] Package_DFN_QFN:QFN-32-1EP_5x5mm_P0.5mm_EP3.8x3.8mm (13)
- [ ] Package_DFN_QFN:QFN-32-1EP_7x7mm_P0.65mm_EP4.65x4.65mm (2)
- [ ] Package_DFN_QFN:QFN-44-1EP_7x7mm_P0.5mm_EP5.2x5.2mm (13)
- [ ] Package_DFN_QFN:QFN-44-1EP_7x7mm_P0.5mm_EP5.4x5.4mm (2)
- [ ] Package_DFN_QFN:QFN-64-1EP_9x9mm_P0.5mm_EP7.25x7.25mm (22)

**Comment by evanshultz** [comment]
Footprint submitted at https://github.com/KiCad/kicad-footprints/pull/434.
