### ISSUE TITLE
Shouldn't Battery_Holders.pretty be moved over or spliced into Battery.Pretty?

### ISSUE THREAD

**Issue by Shackmeister** [KiCad/kicad-footprints#427]
Hi I just noticed practically all of the footprints from Battery_Holders.pretty have been left behind from the big move.
Is there a specific reason for this or has it just been forgotten?

**Comment by poeschlr** [comment]
They have been added in https://github.com/KiCad/kicad-footprints/pull/111
somehow some other commit seems to have deleted them again.

**Comment by poeschlr** [comment]
Ok that one only moved the 3 that are present. Sorry for the noise.

Seems like they have been forgotten after all.

**Comment by evanshultz** [comment]
PR submitted at https://github.com/KiCad/kicad-footprints/pull/429.
