### ISSUE TITLE
Current sense transformers: Manufacturer-specific or not?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-footprints#463]
We have a footprint I added at https://github.com/KiCad/kicad-footprints/blob/master/Transformer_SMD.pretty/Transformer_CurrentSense_8.4x7.2mm.kicad_mod. This footprint fits several different parts.

The PR to submit this footprint was at https://github.com/KiCad/Choke_SMD.pretty/pull/7 and https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/30.

I have a couple questions:
1. Is this footprint name correct? There are a number of different vendors which make compatible parts. How is the best way to name a footprint to fit them? Do we make one manufacturer-specific and assume the user can figure it out (footprint filters should guide them)? Do we use a general footprint with dimensions, like this one, to abstract away the specific vendor info?
2. If we use a generalized footprint, how do we include vendor information? Put multiple datasheets and/or MPNs in the description? Does this info go in the symbol (and then, in both places or only symbol) instead of the footprint?

Small transformers like this are notoriously easy to knock off. All the raw materials are available on the market so if one company builds a desirable part then other competitors can do the same. So a generalized approach seems best to me. But better to ask first as I'd like to add https://www.coilcraft.com/pdfs/cst2010.pdf.

FYI, a discussion about related symbols is at https://github.com/KiCad/kicad-library/pull/837.

**Comment by poeschlr** [comment]
I would use generic footprints where possible. But include all parameters required for identifying the correct 3d model (Even if different trafos share a common landing pattern their height might be different.)

> If we use a generalized footprint, how do we include vendor information? 

In the symbol. (Like we do with all other generic footprints that are used by many different symbols.)

The footprint will still include one reference document. This is intended for sharing the source document for the footprint. (The design specification.) It should help users to find out why a specific footprint looks like it does. (And also us librarians if we ever need to touch the fp again.)
