### ISSUE TITLE
Package_SO.pretty/TSOP-5_1.65x3.05mm_P0.95mm.kicad_mod using pin 6 instead of 5

### ISSUE THREAD

**Issue by MarsWarrior** [KiCad/kicad-footprints#508]
This 5 pin TSOP package uses pins 1,2,3,4 and 6.

The symbols expect pin 5 instead of 6.

**Comment by poeschlr** [comment]
See PR #509

**Comment by MarsWarrior** [comment]
Ah! I was too late entering my own PR :grinning:
