### ISSUE TITLE
Module: Arduino mounting holes too small?

### ISSUE THREAD

**Issue by matthijskooijman** [KiCad/kicad-footprints#590]
Some of the Arduino footprints in the Module library have mounting holes. These holes use a 1.78mm drill size, which seems rather small. For example: https://github.com/KiCad/kicad-footprints/blob/bb3185e1b563b7b3890cd754baaa7d6a8ac32410/Module.pretty/Arduino_UNO_R3_WithMountingHoles.kicad_mod#L96-L99

 Looking at an actual Arduino Uno r3, these have drill holes of around ⌀3mm. Previous (third-party) footprints I've been using also use around 3mm, the [huzza footprint](https://github.com/KiCad/kicad-footprints/blob/master/Module.pretty/Adafruit_HUZZAH_ESP8266_breakout_WithMountingHoles.kicad_mod) has 2.9mm.

@jkriege2, you originally submitted these footprints. Did you intentionally use such small mounting holes?

**Comment by jkriege2** [comment]
sounds more like a mistake ... just post a correcting PR!

**Comment by matthijskooijman** [comment]
@Ratfink, @Shackmeister, thanks!
