### ISSUE TITLE
VSSOP-10 footprint

### ISSUE THREAD

**Issue by sdalu** [KiCad/kicad-footprints#591]
There is currently no vssop-10 footprint

This is used for example by the DRV2605 [1] 

[1] http://www.ti.com/lit/ds/symlink/drv2605l.pdf

**Comment by poeschlr** [comment]
Why make an issue instead of a pull request?

**Comment by sdalu** [comment]
Because I'm not good enough at making footprint

**Comment by poeschlr** [comment]
And you expect somebody else to do your work?

**Comment by sdalu** [comment]
Obviously you don't care about people trying to make contribution at there level of expertise.

**Comment by poeschlr** [comment]
It doesn't help us much if people come here and report missing things. If i sit down for half an hour i bet i can list hundreds of missing footprints or symbols.

If we now accept issues for such missing things we get hundreds of open issues within a short amount of time. This will make our life harder then it needs to be.

If you have questions how to make a footprint you are welcome to ask. If it is a library convention specific question ask here if it is a general how to make a footprint question head over to the forum. (Creating footprints/symbols is one of the most important skills an electronic designer must have. Nobody expects your first contribution to be correct at the first try. This is why you would get feedback from us if you make a pull request.)
