### ISSUE TITLE
Missing DirectFET footprints

### ISSUE THREAD

**Issue by Ratfink** [KiCad/kicad-footprints#608]
To fix https://github.com/KiCad/kicad-symbols/issues/520 for Transistor_FET.lib, we need to create several DirectFET footprints.  All DirectFET footprints are outlined in [International Rectifier Application Note AN-1035](https://www.infineon.com/dgdl/an-1035.pdf?fileId=5546d462533600a40153559159020f76).  The missing packages are listed below to track the progress.

- [x] Package_DirectFET:DirectFET_S3C (https://github.com/KiCad/kicad-footprints/pull/1807)
- [x] Package_DirectFET:DirectFET_SA (https://github.com/KiCad/kicad-footprints/pull/1806)
- [x] Package_DirectFET:DirectFET_SB (https://github.com/KiCad/kicad-footprints/pull/1808)
- [x] Package_DirectFET:DirectFET_MC (https://github.com/KiCad/kicad-footprints/pull/1809)
- [x] Package_DirectFET:DirectFET_MD (https://github.com/KiCad/kicad-footprints/pull/1810)
- [x] Package_DirectFET:DirectFET_MF (https://github.com/KiCad/kicad-footprints/pull/1803)
- [x] Package_DirectFET:DirectFET_L6 (https://github.com/KiCad/kicad-footprints/pull/1805)

**Comment by evanshultz** [comment]
https://github.com/KiCad/kicad-symbols/pull/297

I intended to make a footprint generator that shares input data with the 3D model generator, but it didn't happen yet.

**Comment by evanshultz** [comment]
@Shackmeister 
I know somewhere we talked about the location of the script for the DirectFET footprints merged at https://github.com/KiCad/kicad-packages3D/pull/143. You mentioned perhaps the input parameters (YAML file?) could be shared between the footprints and the 3D models. I'm ready to make the footprints now so I wanted to find this conversation.

Alas, I can't find it no matter how hard I look. I also don't find anything in the 3D source or at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts. Argh! Can you point me to the location of the scripts for these 3D models?

**Comment by Shackmeister** [comment]
Hi Evan I made the footprints manually and scripted the 3D models.
https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator/Directfet_SMD

**Comment by evanshultz** [comment]
All footprints have been merged and the PR noted in the first comment.
