### ISSUE TITLE
Archive legacy repositories

### ISSUE THREAD

**Issue by pointhi** [KiCad/kicad-footprints#64]
@SchrodingersGat 
What about marking the legacy repositories as read-only, to prevent contributors making pull requests on no longer maintained repositories? https://help.github.com/articles/archiving-a-github-repository/

**Comment by poeschlr** [comment]
I did not know this is possible. Good idea.

**Comment by SchrodingersGat** [comment]
@pointhi I also did not know that this was possible. Thanks for the idea :)
