### ISSUE TITLE
Current 0402 footprint is wrong!

### ISSUE THREAD

**Issue by jcyrax** [KiCad/kicad-footprints#660]
After https://github.com/KiCad/kicad-footprints/pull/642 new 0402 is obviously wrong with spacing of 0.08mm between pads. I found that there is error in size definition file in https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/SMD_chip_package_rlc-etc/size_definitions/size_default_chip_devices_smaller_0603.yaml terminator_spacing_min: 0.1 is wrong, there needs to be 0.4mm, if you look in linked document. 
![image](https://user-images.githubusercontent.com/16546947/41416347-4a94c2b6-6ff3-11e8-9b48-6f2b812b892e.png)
Obviously mistake copying values and T value used instead of S. It looks like its been like this for some time now, just recent changes made it obvious.

**Comment by poeschlr** [comment]
fix is part of https://github.com/KiCad/kicad-footprints/pull/653

**Comment by poeschlr** [comment]
and this pr https://github.com/KiCad/kicad-footprints/pull/656 fixes it for the v4 backport

**Comment by evanshultz** [comment]
@jcyrax 
Both PRs above are merged. Can you please confirm this issue is fixed?

**Comment by jcyrax** [comment]
Can confirm, this is fixed now.
