### ISSUE TITLE
MPT Phoenix Terminal block generates assert on 3d viewer

### ISSUE THREAD

**Issue by FabianInostroza** [KiCad/kicad-footprints#672]
When viewing the following footprints 
TerminalBlock_Phoenix_MPT-0,5-2-2.54_1x02_P2.54mm_Horizontal.kicad_mod
TerminalBlock_Phoenix_MPT-0,5-3-2.54_1x03_P2.54mm_Horizontal.kicad_mod

in the 3d viewer there are some asserts that fail.
The reason is that these footprints contain NPTH with zero size

**Comment by poeschlr** [comment]
The script for these is build kind of wrong. (uses size 0 do indicate NPTH instead of using the drill size for that.)

**Comment by poeschlr** [comment]
I discovered another problem with the script. It adds pin numbers to NPTH drills.

**Comment by FabianInostroza** [comment]
Seems you already fixed this, thanks @poeschlr
