### ISSUE TITLE
Library for LEM LV 25-P

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-footprints#694]
At https://github.com/KiCad/kicad-footprints/pull/620#issuecomment-399798831 I said:

> One other question: Should we have a new library called `Sensor_Voltage` since `LEM_LV25-P` is voltage transducer and not for current measurement? Not in this PR, but as I was looking at this it seems like the correct way to go.

Isn't that correct?

Datasheet: https://www.lem.com/sites/default/files/products_datasheets/lv_25-p.pdf

**Comment by poeschlr** [comment]
Well the first thing that i can read in the datasheet is that this is indeed a voltage transducer. So yes it should be in the lib named Sensor_Voltage. (Adding libs is allowed even after the v5 release.)

**Comment by evanshultz** [comment]
Right, but then `Sensor_Voltage` would include only one footprint. OK?

Relatedly, we have this library for symbols and it contains only the matching symbol. Just FYI.

**Comment by poeschlr** [comment]
I would guess there will come more in future.

**Comment by evanshultz** [comment]
Symbol and footprint PRs made and linked above. Closing this now.
