### ISSUE TITLE
PCB fabrication tolerance question

### ISSUE THREAD

**Issue by jcyrax** [KiCad/kicad-footprints#696]
I noticed that footprint generation scripts formulas use F (printed board fabrication tolerances) value of 0.1mm. This is same as IPC-7351B and even previous version from ~2005.

Page 15 in IPC-7351B says that you can set this to 0 if manufacturer has accounted for this by "swelling" features.

Should it be set to 0?

**Comment by poeschlr** [comment]
I think we should be a bit conservative here. As we do not know what our users will do with the footprints. So i personally vote for 0.1mm.
