### ISSUE TITLE
Converter_ACDC: IRM-02 SMD footprint has wrong dimensions

### ISSUE THREAD

**Issue by antoniovazquezblanco** [KiCad/kicad-footprints#749]
http://www.meanwell.com/webapp/product/search.aspx?prod=IRM-02

![imagen](https://user-images.githubusercontent.com/304193/42763537-a6445a98-8913-11e8-9087-75788af61b90.png)

Instead of that, the current body is 22.3x37mm

**Comment by antoniovazquezblanco** [comment]
Moreover it cannot have the same symbol as the non SMD version due to pin numbering mismatches 🤦‍♂️

**Comment by antoniovazquezblanco** [comment]
@Misca1234 Can you handle the update of the 3D generation script and 3D model please? :)

**Comment by Misca1234** [comment]
Sure, le me have a look at it
Was a while ago

**Comment by Misca1234** [comment]
script push is here
https://github.com/easyw/kicad-3d-models-in-freecad/pull/187

3D model push is here
https://github.com/KiCad/kicad-packages3D/pull/342

**Comment by antoniovazquezblanco** [comment]
Thank you very much!

**Comment by antoniovazquezblanco** [comment]
Footprint fixed
