### ISSUE TITLE
Inductor THT: Missing 3d model references, second reference (fab) interferes with fab and some silk lines on top of pads.

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-footprints#76]
This is ideally fixed within the generator scripts directly. (Fixing the inductor references would also fix some of the resistor references because they share the same generator scripts.)
So https://github.com/KiCad/kicad-footprints/issues/74 is related in part to this issue.

Script location: https://github.com/pointhi/kicad-footprint-generator

**Comment by poeschlr** [comment]
@Shackmeister did you close the wrong issue? The linked pull request does not touch inductor footprints but resistors.

**Comment by Shackmeister** [comment]
Yes I closed the wrong issue, sorry

**Comment by poeschlr** [comment]
Fix merged
