### ISSUE TITLE
Number of positions does match part number in Samtec HLE footprints 

### ISSUE THREAD

**Issue by mikelawrence** [KiCad/kicad-footprints#776]
For example the "Samtec_HLE-108-02-xxx-DV-BE-A_2x04_P2.54mm_Horizontal.kicad_mod" footprint indicates it is a 2x04 footprint but the HLE-108-02 part is a 2x08. The footprint matches the description of 2x04. So this footprint should have been called "Samtec_HLE-104-02-xxx-DV-BE-A_2x04_P2.54mm_Horizontal.kicad_mod". The XX in HLE-1XX indicates the number of positions in a row.

This issue seems to be present in both "Connector_Samtec_HLE_SMD" and "Connector_Samtec_HLE_THT" libraries.

**Comment by poeschlr** [comment]
Scripts for these are found here: https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Connector/Connector_Samtec/conn_samtec_hle.py

**Comment by evanshultz** [comment]
@mikelawrence 
Thanks for the bug report! Fix is merged now.
