### ISSUE TITLE
Pad position resolution 

### ISSUE THREAD

**Issue by therman89** [KiCad/kicad-footprints#784]
The new footprint libraries use a resolution of 0.0005mm, which is not
supported by pcbnew's grid list, nor does it make sense. It makes
distancing very difficult. Please update footprint libraries, so that
they use a resolution, that actually makes sense. E.g. 0.05mm, as in
previous versions.
![image](https://user-images.githubusercontent.com/10553343/43164655-fb7a9dd6-8f91-11e8-9af7-cb429d75935d.png)

**Comment by poeschlr** [comment]
PCB_New does not rely on the grid to create traces. (The trace snaps to the center anyways.) So this should not matter at all.

The reason for these positions is that some footprints are created in accordance with IPC which specifies a rounding resolution of 0.05mm for the spacing between pads (Dimension S) which means the position of the pad will then be on 0.05/4 = 0.0125mm grid.
