### ISSUE TITLE
Fuse: Typo at Littlefuse

### ISSUE THREAD

**Issue by jstjst** [KiCad/kicad-footprints#808]
Litt**le**fuse should be Litt**el**fuse
http://www.littelfuse.com

Affecting Names and also Keywords/Doc fields

Same Typo in the KLC: https://github.com/KiCad/kicad-website/issues/314

**Comment by Ratfink** [comment]
Oh heck, that's embarrassing.  Thanks for pointing out the problem!  The fix is submitted as #809.

**Comment by jstjst** [comment]
Made this typo myself, noticed it while googleing
