### ISSUE TITLE
JAE LY connectors

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-footprints#82]
@SchrodingersGat 
I assume https://github.com/KiCad/Connectors_JAE.pretty/pull/3 had a scripted family of these connectors but it didn't get merged. While these might be a few more tweaks to make, it seems a waste to never add these footprints.

**Comment by poeschlr** [comment]
Have been added in https://github.com/KiCad/kicad-footprints/pull/147
The script will be added with https://github.com/pointhi/kicad-footprint-generator/pull/91
