### ISSUE TITLE
ErrType(19) - Pad near Pad issue with Resistor_SMD:R_Array_Convex_4x0402

### ISSUE THREAD

**Issue by leoheck** [KiCad/kicad-footprints#973]
I am using `Resistor_SMD:R_Array_Convex_4x0402` and I always receive this `Pad near Pad` issue on PCBNew

![image](https://user-images.githubusercontent.com/1277920/46101554-a57b8b00-c1a2-11e8-9d26-e35d14d05cd1.png)

I tried to reduce the track width to fix it. But nothing has happened. Now, it is 0.05 mm (1.97 mil) and I still have the Pad near Pad issue.

Any idea on how to fix it?

![image](https://user-images.githubusercontent.com/1277920/46101514-84b33580-c1a2-11e8-8222-f2bae0fc3e4e.png)

**Comment by Shackmeister** [comment]
That is a matter of board/DRC setup.
Since its pad to pad and not track to pad, the tracks has nothing to do with it

**Comment by evanshultz** [comment]
This repo is for discussing the libraries. One good place to post "using KiCad" questions is on the forum: https://forum.kicad.info/.

The constraint being violated is pad-pad spacing, so of course changing the track parameters won't help. This is controlled by the Clearance parameter in the Design Rules.

**Comment by leoheck** [comment]
Thanks @evanshultz
